version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: movieapi
    ports:
      - 3000:80
    volumes:
      - /usr/app/node_modules
      - .:/usr/app/
    links:
      - mongodb

  mongodb:
    image: mongo:4.2
    container_name: mongodb
